FROM ubuntu:<%= ENV.fetch 'TAG' %>
MAINTAINER Frank Macreery <frank@macreery.com>

ADD files/usr/bin/apt-install /usr/bin/apt-install

# Install latest security updates now, and on build
# During build, we use AllowRedirect to fix 4371-1.

RUN SECURITY_LIST=$(mktemp) \
 && grep security /etc/apt/sources.list > "$SECURITY_LIST" \
 && apt-get -o "Dir::Etc::SourceList=${SECURITY_LIST}" -o Acquire::http::AllowRedirect=false update \
 && apt-get -o "Dir::Etc::SourceList=${SECURITY_LIST}" -o Acquire::http::AllowRedirect=false upgrade -y \
 && rm -rf /var/lib/apt/lists/* \
 && rm "$SECURITY_LIST"

ONBUILD RUN SECURITY_LIST=$(mktemp) \
 && grep security /etc/apt/sources.list > "$SECURITY_LIST" \
 && apt-get -o "Dir::Etc::SourceList=${SECURITY_LIST}" update \
 && apt-get -o "Dir::Etc::SourceList=${SECURITY_LIST}" upgrade -y \
 && rm -rf /var/lib/apt/lists/* \
 && rm "$SECURITY_LIST"

# Install Git and tzdata. Those are usually needed in customer containers.
RUN apt-install git tzdata

# Install Bats
RUN git clone https://github.com/sstephenson/bats.git /tmp/bats && \
    cd /tmp/bats && ./install.sh /usr/local

# Integration tests
ENV LIBC_MIN <%= ENV.fetch 'LIBC_MIN' %>
ENV LIBSSL_MIN <%= ENV.fetch 'LIBSSL_MIN' %>
ADD test /tmp/test
RUN bats /tmp/test
